### ISSUE TITLE
ActionBar

### ISSUE THREAD

**Issue by hermandinho** [hamdiwanis/nativescript-app-tour#12]
Hello, please seems this plugin does not work for items in ActionBar. I am using Andular. It works fine for items on the page

**Comment by standevo** [comment]
I have the same problem

With the custom elements working fine except ActionItems inside ActionBar

Please help.

**Comment by dlcole** [comment]
I can get this to work on iOS, but not on Android.  Mine is a JavaScript project; the action bar looks like this: 

```
<Page.actionBar>
    <ActionBar title="{{eventData.appName}}" icon="" class="action-bar">
      <ActionBar.actionItems>
        <ActionItem ios.position="right" tap="onMenuTap" android.systemIcon="ic_menu_moreoverflow_normal_holo_dark">
          <ios>
            <ActionItem.actionView>
              <StackLayout>
                <Label id="moreIcon" text="  &#xf142; " class="action-item-font"/>
              </StackLayout>
            </ActionItem.actionView>
          </ios>
        </ActionItem>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>
```

In iOS I can use the 'moreIcon' ID, but on Android, there's no place to attach an ID, best I can tell. 

This is a big limitation, because pointing to actions in the action bar is something you'd want to highlight in an app tour.

**Comment by hamdiwanis** [comment]
@dlcole i don't see why the id cant be set on android, did you try setting the id on the label container instead

**Comment by dlcole** [comment]
Yes, the label container works for iOS, but note that the label is for iOS only.  Android uses a system icon, and I'm not able to set an id property on the `ActionItem` tag.  

I'd welcome any suggestions here, including alternatives to how action items can be included in the action bar so that they can be id'ed for a tour.

**Comment by hamdiwanis** [comment]
@dlcole I just tried custom action item on android and it worked fine 

```
   <ActionBar>
        <ActionItem>
            <Image id="ActionItemImageId" src="res://icon" class="action-image">
            </Image>
        </ActionItem>
    </ActionBar>
```
then
`page.getViewById("ActionItemImageId");`

**Comment by hamdiwanis** [comment]
Also, I see the native library used has issues with old action bar so you might run into this issue https://github.com/KeepSafe/TapTargetView/issues/168 where you will have to wait for sometime before you can start the tour

**Comment by dlcole** [comment]
I modified my code to not use the Android system icon and now is: 

```
      <ActionBar.actionItems>
        <ActionItem ios.position="right" tap="onMenuTap">
            <ActionItem.actionView>
              <StackLayout orientation="horizontal">
                <Label id="moreIcon" text="  &#xf142;" class="action-item-font"/>
                <android>
                  <Label text="   " class="action-item-font" />
                </android>
              </StackLayout>
            </ActionItem.actionView>
        </ActionItem>
      </ActionBar.actionItems>
```

This now works on both iOS and Android!  I added the extra label on Android for padding but could just have easily done so in platform-specific css.

Thanks!
