### ISSUE TITLE
Stop appears under dialog

### ISSUE THREAD

**Issue by bzaruk** [hamdiwanis/nativescript-app-tour#6]
Hi @hamdiwanis,

I have a modal dialog that I want to put an tour on it, and the stop balloon in found under the dialog.
As you can see here - 
![screenshot_1540513010](https://user-images.githubusercontent.com/27296296/47537343-dc41df80-d8cd-11e8-8c01-ded60b882970.png)

I really think that is about this [line](https://github.com/hamdiwanis/nativescript-app-tour/blob/e247007c62311da218bb9e5e4437840340f50c19/src/app-tour.android.ts#L26) - as I understand it expect to get and activity but the foregroundActivity is not the needed one.

do have any idea what could it be?

Thanks a lot! :)

**Comment by hamdiwanis** [comment]
hey @shabib3 yes you are right the problem is in the case of a modal it uses the wrong activity, the first solution that came to my mind is allowing the user to pass the activity they want to the plugin setup fn and have foreground activity as default but I don't know maybe there is a better solution that will allow for the plugin to know it's being used in a modal, so I will look it up when I have time , and as I don't think that will be soon (sorry for that ) I will appreciate any PRs :)

**Comment by bzaruk** [comment]
I tried to investigate it some and saw this - https://github.com/KeepSafe/TapTargetView#sequences

yes it appears that it should get other activity...

**Comment by hermandinho** [comment]
Any update please?

**Comment by soscler** [comment]
Any update ?
